baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Taskun'
theme = 'hermit-v2'


[menu]

# [[menu.main]]
#   name = "Posts"
#   url = "posts/"
#   weight = 10

# [[menu.main]]
#   name = "About"
#   url = "about-hugo/"
#   weight = 20

[[menu.main]]
name = "Terms of service"
url = "terms_of_service/"
weight = 20

[[menu.main]]
name = "Privacy policy"
url = "privacy_policy/"
weight = 20

[params]
dateform = "Jan 2, 2006"
dateformShort = "Jan 2"
dateformNum = "2006-01-02"
dateformNumTime = "2006-01-02 15:04 -0700"

# Metadata mostly used in document's head
description = "A Telegram bot which helps you to create google calendar events and tasks with ease"
# images = [""]
themeColor = "#494f5c"
accentColor = "#018472"

homeSubtitle = "A Telegram bot which helps you to create google calendar events and tasks with ease"
#footerCopyright = ' <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
# bgImg = ""
# gitUrl = "https://github.com/1bl4z3r/hermit-V2/tree/staging"

justifyContent = false

relatedPosts = true
code_copy_button = true

homeSubtitlePrinter = true
scrollToTop = true
global_mathjax = false
readTime = true
readTimeSeparator = "\u2026 \u23F2 Reading Time:"
# legacyLayout = false
shareSocial = true
# googleTagManager = "GTM-XXXXXXXX"
# tagSymbol = "#"
# categorySymbol = "⊲"
pinned = "Pinned Posts"
# pinnedSVGname = "pin"
descriptionInPosts = true
# initialPublish = "Initally Posted on: "
#human = ["single","posts"]
# denyRobots = "noindex, nofollow, noarchive"
# allowRobots = "index, follow"
# siteNoIndex = false
# noIndexPages = ["404 Page not found"]
footerHideThemeName = true
usesAnimation = true

# [[params.socialLinks]]
#   name = "github"
#   url = "https://github.com/1bl4z3r/hermit-V2/tree/staging"
